### ISSUE TITLE
SMS message not sending

### ISSUE THREAD

**Issue by AustinDeric** [awslabs/aws-mobile-react-sample#26]
Similar to issue #16, 

I am not able to receive sms messages. I have aws-exports.js in my src directory and i confirmed that user-signin is enabled in awsmobile features.

**Comment by AustinDeric** [comment]
I see that cognito says:

```
Important: In order to send SMS messages to users to verify phone numbers or for MFA you must request a spending limit increase from Amazon SNS. Learn more. 
```
and also
```
You must provide a role to allow Amazon Cognito to send SMS messages

Amazon Cognito needs your permission to send SMS messages to your users on your behalf.
```

However it is not at all clear how do to this.   Hopesfulyl when i fgure it out i will be able to share. Thanks!

**Comment by AustinDeric** [comment]
Solved.

The phone number must be in the format +WXXXYYYZZZZ:
- W is the country code
- XXX is the zip code
- YYYZZZZ is the phone number

This may be obvious to experienced devs, but it wasn't too me.  I am considering updating the readme to be clear or the react app to provide better feedback to the user.

**Comment by lwilli** [comment]
@AustinDeric I'm having the issue of it not sending texts, but I double checked the format and it still isn't working. I have tried both with running locally (awsmobile run) and with publishing it (awsmobile publish). What exactly did you have to do to get it to work? I can see the Cognito is creating new identities, but it's not sending SMS messages.

**Comment by elorzafe** [comment]
Hi @lwilli can you paste mobile-hub-project.yml that is on awsmobilejs/backend/ folder?

**Comment by lwilli** [comment]
Hi @elorzafe. Here's my mobile-hub-project.yml. Thanks for taking a look.

```
--- !com.amazonaws.mobilehub.v0.Project 
apps:
  web: !com.amazonaws.mobilehub.v0.AppDO {}
features:
  content-delivery: !com.amazonaws.mobilehub.v0.ContentDelivery 
    attributes:
      enabled: true
      visibility: public-global
    components:
      release: !com.amazonaws.mobilehub.v0.Bucket {}
  mobile-analytics: !com.amazonaws.mobilehub.v0.Pinpoint 
    components:
      analytics: !com.amazonaws.mobilehub.v0.PinpointAnalytics {}
      messaging-email: !com.amazonaws.mobilehub.v0.PinpointMessaging 
        attributes:
          deliveryType: email
          emailDomain: 415941446547636e427877656a46467538634b6c444f56664f6a5141655141434141706859324e76645735304c576c6b414177314f4459774d54497a4d5449774f446741465746336379316a636e6c77644738746348566962476c6a4c57746c6551424551585661546e6b3263453035626d644c515649315a6c706c5a565243554531326447563156586c5855564e70557a5a7a537a5a32557a6c71574530775a56426e654546735a32784c644841316557354b544442586447644250543041415141485958647a4c5774746377424c59584a754f6d4633637a707262584d3664584d745a57467a644330784f6a517a4e7a41354d446b354d44597a4e5470725a586b764e7a68694d3255314e5467744f474e6b5a5330304d5751334c5467345a444d744d7a466a5954526c5a446b305a475134414b6342415145416548576a726a4f5974744532443062336d2f3661456f55617a61414777487a796535774350734f712f4b695a41414141666a423842676b71686b69473977304242776167627a4274416745414d4767474353714753496233445145484154416542676c67686b67425a514d45415334774551514d7675793475614a6558655834454a664c4167455167447350507a54336d4d4d6f4f42684c444f3441514b7633416173336273635a38576357324d31437a467369657349613347336b3532336f68615950304b38646b56626e5447335478775254586c5858545149414141414144414141454144515672527a423445554d2b717242664872373671696a33746667445a53555472316847326c2f2f2f2f2f774141414146504837727647554474576b646b596673414141414b4974554a663639632f4e342b634759632f443875317945376773666b346d6565593059415a7a426c416a42424b4a4a324d4e5334766550567156436d3071614c6e776947687a4e75484b4f2f336b584138735a55382f6c5662416b5942456235426f6e5130366c596f3238434d5144375635612b426f66416e4a645153443475694176556c6431414d477567706b4a62327250557a73366670474a69486941553961765a5a7a5273456566494653773d
          emailID: 41594144654e5659744b3852564f30354f57474c666f394a51573841655141434141706859324e76645735304c576c6b414177314f4459774d54497a4d5449774f446741465746336379316a636e6c77644738746348566962476c6a4c57746c655142455157313155304e58615551724d7a4a795257645252327377537a677764304a53536b4a6d635442704e306c4b6247396b5445557a5233686854793957636c427662456c46596e646d59566c77556a46455547565351325a6e50543041415141485958647a4c5774746377424c59584a754f6d4633637a707262584d3664584d745a57467a644330784f6a517a4e7a41354d446b354d44597a4e5470725a586b764e7a68694d3255314e5467744f474e6b5a5330304d5751334c5467345a444d744d7a466a5954526c5a446b305a475134414b6342415145416548576a726a4f5974744532443062336d2f3661456f55617a61414777487a796535774350734f712f4b695a41414141666a423842676b71686b69473977304242776167627a4274416745414d4767474353714753496233445145484154416542676c67686b67425a514d45415334774551514d7a636c46536e6d364b645746552b4f46416745516744745748334e6e6e74524e374b322b54443342732b423745384c734a5749434c734c6a5843336a7a796a4b2b3069597a453879387646516c6e77744b63647a65426453736b436730433136306c6a466b51494141414141444141414541425731334f4a6550796549504a38726c5157724f75722f68794b42736d37745972392f4e414b2f2f2f2f2f774141414148646d6932566e52754337666b73503763414141414b62436642412b545a4d34612f54734643316953364d5767356c444e726d514f65574449415a7a426c416a42496f6d5a31615a30704e514a504d46664a4b515945436b49595536484c516d643471317a77534e3146443030335667676442544c52394e652f5a6e5063553041434d51444866496e59716a4c4132385a64734e51663657766f686443457455526932556b6c426f2f6c35706f6c614a427a46303930686f2b4130677766723465414f53773d
      messaging-sms: !com.amazonaws.mobilehub.v0.PinpointMessaging 
        attributes:
          deliveryType: sms
  sign-in: !com.amazonaws.mobilehub.v0.SignIn 
    attributes:
      enabled: true
      optional-sign-in: true
    components:
      sign-in-user-pools: !com.amazonaws.mobilehub.v0.UserPoolsIdentityProvider 
        attributes:
          alias-attributes:
            - email
          mfa-configuration: OFF
          name: userpool
          password-policy: !com.amazonaws.mobilehub.ConvertibleMap 
            min-length: '8'
            require-lower-case: true
            require-numbers: true
            require-symbols: true
            require-upper-case: true
name: TestProject
region: us-east-1
```

**Comment by ciseburg** [comment]
Same issue as @lwilli. Any tips @AustinDeric or @elorzafe ?

**Comment by filanthropic** [comment]
When typing in your phone number, make sure its E.164 compliant: +12028675309.

**Comment by elorzafe** [comment]
Hi @lwilli did you still have this issue?

**Comment by lwilli** [comment]
Hi @elorzafe, I posted by mobile-hub-project.yml file, but didn't get any feedback...

**Comment by moonbread** [comment]
Hi @lwilli -- I had this same issue until I realized that the password I was entering didn't meet the default Cognito specifications of minimum length 8 characters and including numbers, special character, upper & lower-case letters. After entering a valid password, the notifications came through fine for me,

**Comment by elorzafe** [comment]
I realized that you dont have MFA enabled on your project
```
      sign-in-user-pools: !com.amazonaws.mobilehub.v0.UserPoolsIdentityProvider 
        attributes:
          alias-attributes:
            - email
            - phone_number
          mfa-configuration: ON
          name: userpool
          password-policy: !com.amazonaws.mobilehub.ConvertibleMap 
            min-length: '8'
            require-lower-case: true
            require-numbers: true
            require-symbols: true
            require-upper-case: true
```

Please let me know how it goes
